### ISSUE TITLE
Reconfiguring default loadouts

### ISSUE THREAD

**Issue by calumbrookes** [CombinedArmsGaming/F3_CA#11]
Changing the default loadout parameter to light so that individuals have less to carry regularly, and removing backpacks where possible.

**Comment by jimshacklock** [comment]
WRT to this, IMO the best way to do it would be to comment out backpack assignment for any role that's lighter than an AR by default. Reworking all the loadouts for the Light loadout is a bit of a faff and also takes into account armour and everything. 

Can we get a decision on which roles should/shouldn't have backpacks?
My suggestions are:

co - Y (LR Radio)
dc - Y (LR Radio)
m - Y (Medkit) 
ftl - Y (Fireteam Supplies)
ar - **N (AR is heavy already, and gives more value to AAR, and promotes teamwork)**
aar - Y (AR Ammo, makes assistant more valuable if gunner has less ammo)
rat - N
dm - N
mmgg - **N (MMG is heavy already, and gives more value to AAR, and promotes teamwork)**
mmgag - Y (MMG Ammo, makes assistant more valuable if gunner has less ammo)
matg - Y (Can't really carry many rounds anyway, needs both team members carrying ammo IMO)
matag - Y (Can't really carry many rounds anyway, needs both team members carrying ammo IMO)
hmgg - Y (Deployable Weapon)
hmgag - Y (Deployable Tripod)
hatg - Y (Deployable Weapon)
hatag - Y (Deployable Tripod)
mtrg - Y (Deployable Weapon)
mtrag - Y (Deployable Tripod)
msamg - Y (Can't really carry many rounds anyway, needs both team members carrying ammo IMO)
msamag - Y (Can't really carry many rounds anyway, needs both team members carrying ammo IMO)
hsamg - Y (Deployable Weapon)
hsamag - Y (Deployable Tripod)
sn - N
sp - N
vc - N
vg - N
vd - Y (Toolkit)
pp - N
pcc - Y (Toolkit)
pc - N
eng - Y (Toolkit/Eng equipment)
engm - Y (Toolkit/Eng equipment)
uav - Y (UAV Bag)
div - Y (We never really use these anyway, but rebreathers/wetsuits cannot carry much gear)
r - N 		
car - N			
smg - N			
gren	- N

**Comment by Poulern** [comment]
I'd like to get rid of the backpack part of the gear script altogether, i find it adds more confusion that it solves.

**Comment by jimshacklock** [comment]
So just add it into the main script rather than have them as separate
classes called for each unit?

Might also be worth looking at the updated F3 implementation. From what I
can remember they've broken the light/med/heavy out into a couple of
separate gearscripts

**Comment by jimshacklock** [comment]
At this stage I think this can be closed - It's not a significant enough change to warrant a framework level one, and if Poulern is intending on doing a rework of the gearscript in general then we can ditch this.
