### ISSUE TITLE
ACRE2 merger

### ISSUE THREAD

**Issue by calumbrookes** [CombinedArmsGaming/F3_CA#12]
Does your ACRE2 branch convert the framework to being ACRE2 as the default radio or does it add it as an option?

Would be nice to have the newer F3 ACRE functionality merged into our older F3 framework so that the radio plugin parameter is all that you need to set up to decide between the two

**Comment by jimshacklock** [comment]
The ACRE branch at current does set it as default, however it's literally
just changing one value in the description.ext to reset that back to TFAR.
That said I'm not 100% sure how stable the current build on here is - I'll
grab it and recheck it against the local build I've got as there's some
changes I've made locally.

**Comment by calumbrookes** [comment]
Ok so we could actually merge the branches and make F3_CA suitable for both radio plugins as soon as you've made sure it's stable?

**Comment by jimshacklock** [comment]
Yup, it won't affect current TFAR stuff at all

**Comment by calumbrookes** [comment]
Awesome, I say we go ahead with that then as the sooner we have a combined framework the better - it'd make our missions basically cross-compatible too which is a nice feature.

**Comment by jimshacklock** [comment]
I've set up a stable release of the framework for ACRE2 now, and merged it back into main - This should be good to go, but if anyone can test it I'd appreciate it.

**Comment by calumbrookes** [comment]
Issue Closed.
