### ISSUE TITLE
ACRE2 Framework isn't recieving groupIDs properly

### ISSUE THREAD

**Issue by jimshacklock** [CombinedArmsGaming/F3_CA#16]
The framework for ACRE2 isn't receiving the groupIDs for units correctly, so everyone still gets the "Unknown group" error when starting a mission. Automatic channel assignment also does not work without this. 

AFAIK this now should work with the changes Poulern made to the groupIDs, but for some reason it still doesn't.

Needs further investigation.

**Comment by Poulern** [comment]
Fixed in dacedb9ceb19174206d8a0007f967801b75a45bd
