### ISSUE TITLE
ACRE settings in the framework are being overwritten by server side settings

### ISSUE THREAD

**Issue by jimshacklock** [CombinedArmsGaming/F3_CA#19]
The settings defined in f/radios/acre2/acre2_settings.sqf currently seem to be overwritten by the server side settings in game. This may explain some of the issues we've had w/ signal loss (e.g. the Marders/Shermans). 

Need to investigate how to prevent this from happening and how to set it up for the mission file to always take priority over server/client settings.

**Comment by calumbrookes** [comment]
I can provide or change server settings on requirement to assist with this

**Comment by jimshacklock** [comment]
That is a solution, but it's ultimately a plaster on the issue rather than actually fixing the problems root. It also limits the missionmaker to being stuck to those settings which I'd like to avoid just in case. 

If it comes down to it we can go ahead with that as it is a fix, just not the ideal one

**Comment by DutchVidya** [comment]
For what it's worth, we can keep adjusting these as we go, that Configure Addons screen contains everything we need.

Has F3 changed anything itself and we just haven't noticed?

**Comment by jimshacklock** [comment]
At this point we're so far off the main F3 build it's hard to track really. I'm not aware that they've done any updates in one time though, particularly WRT acre/radios

**Comment by DutchVidya** [comment]
I checked, no changes. Then only thing I can think is that they have ceased devlopment of it as the menu we have in game works as is.

**Comment by calumbrookes** [comment]
@jimshacklock did we ever resolve this?

**Comment by jimshacklock** [comment]
Nope, I'd say it became a shippable issue once we updated the server settings to fit with what we actually wanted. I don't feel like we've encountered any issues to the original level since that fix, so I'm tempted to say we can close this.

**Comment by calumbrookes** [comment]
Closing this as discussed
