### ISSUE TITLE
Radio channels are desynched

### ISSUE THREAD

**Issue by Poulern** [CombinedArmsGaming/F3_CA#67]
I am not sure where to begin, so starting an issue to track updates. This issue has been reported in a limited capacity multiple times, but kind of written off.

Sat 04 JULY 343 radios weren't correctly set. This caused people to not hear eachother, despite being on the same channel. Sometimes it would drift in and out. This was in the middle of a field with no obstacles. 

Anyone have any idea where to begin? Could radio frequencies be desynched? Are radio assignments broken? Babel kicking for some reason?

Suspects (Could be multiple reasons):

* Set radio channels in hierachy interface causing issue. However this is only for 343s, and LR also have issues. 

* Radios received on respawn/picked up being somehow different or respawned players acting different. 

* Specific players having issues - outdated acre2 dlls, other software. Buckethead consistently having this issue for example. I find this to be highly unlikely as a lot of players have had this issue.

* Some ACRE2 setting being wrong somewhere.

**Comment by Rqller** [comment]
Could it be that the way the framework assigns radios and frequencies is doing... something? I've noticed a few times, that if you pick up a radio from a crate it is not assigned the same frequencies. Only  the radios spawned/assigned through the framework have the framework-frequencies.

**Comment by jimshacklock** [comment]
The biggest change to anything related to acre2 stuff recently is this one:

https://github.com/CombinedArmsGaming/F3_CA/commit/49ad490c3b20052581838da4e5bca564e2ee61c9#diff-e8361a90c382866198aa642529c3bd43

I'm tempted to put the blame on the fact that radios are being assigned channels that are unnecessarily high in the range (Ch50+), as this all worked fine previously before we started assigning out stuff that high (I'm also still not convinced of the need for having so much stuff preset in there as it's just unused data that bloats out the framework, but I know Poulern's already resolved this in dev branch).

WRT to the frequency thing Klima mentioned - I'll check server/mission addon settings now see if anything's configured weirdly

**Comment by Poulern** [comment]
This was happening on block 1 channel 1-4, but people did start out with 51-52. I don't think I am ready to point to that as the cause though, it seems too random to break things.

**Comment by Poulern** [comment]
So I thought I had another incident in HaM yesterday where someone called for another group over 343, while they were 50m away and didn't respond. When we walked over there it turned out only one had a 343 and he said he didn't hear us (as in was not sure if the radio traffic he was hearing was directed at him), and could hear the 343 when i tested it there on the stop (Though I wasn't able to clear if he could hear the original callers 343).

I am still not sure if this is just bad ears or if it was the same issue we had. The Terrain loss was set to 0. This ambiguity is what is making it hard to nail down what or when things are happening.

**Comment by Poulern** [comment]
@Bubbus mentioned after issues with yesterdays op that its because of acre2 terrain loss on cup maps that dont support terrain loss. Given its apparently common knowledge i am willing to add some force terrainloss off in cba_Settings to solve the issue once and for all.

**Comment by Poulern** [comment]
Fixed insofar as terrain loss has been disabled as a server setting by default. I've not heard any issues with it since. If any MMs want to use terrain loss beware of these issues.
