### ISSUE TITLE
CSAT Patches need added.

### ISSUE THREAD

**Issue by calumbrookes** [CombinedArmsGaming/F3_CA#7]
Raising issue as a future reminder that the IND & BLU patches are complete but the OPF ones are not.

**Comment by jimshacklock** [comment]
Do we want these to be standard Alpha/Bravo/Charlie, or do we want Anna/Boris/Chariton? Can always create both but it'll take a bit longer to create and set up.

**Comment by calumbrookes** [comment]
Does that matter? Surely the patches say A B C not the full word?

**Comment by jimshacklock** [comment]
No, they say the full word - Went through some iteration and just having the letter did not work as well with the design/look as good

**Comment by calumbrookes** [comment]
Right. I think probably Anna Boris Chariton then as if we're opfor we're basically always russians or CSAT right?

**Comment by jimshacklock** [comment]
CSAT patches added, with generic alternates.
Also added template and removed CSAT_Urban as it's redundant.

CL 7f8afc1
