### ISSUE TITLE
[Dev Branch] Add HC addon settings to cba_settings.sqf

### ISSUE THREAD

**Issue by thepaullee** [CombinedArmsGaming/F3_CA#76]
Ideally set and overridden by Server addon settings but this is a good backup in case not

// ACEX Headless
acex_headless_delay = 15;
force acex_headless_enabled = true;
acex_headless_endMission = 0;
acex_headless_log = false;
force acex_headless_transferLoadout = 1;

**Comment by Poulern** [comment]
What are the defaults. What happens if you have these settings on while not running a HC?

**Comment by thepaullee** [comment]
Default is to have ACEX Headless disabled, which in most cases where the MM hasn't added an AI load balancer means we have an unused HC connected to the server

Having the setting enabled without an HC connected is no problem, to reproduce try enabling it and running a mission on your own machine in the MP editor. If a HC connects mid mission the module still load balances the AI

**Comment by Poulern** [comment]
Add it as an commit to the latest #79 , preferably with forcing terrain loss off as well.
