### ISSUE TITLE
new assignGear class consistencies

### ISSUE THREAD

**Issue by thepaullee** [CombinedArmsGaming/F3_CA#80]
Unit init fields in mission.sqm need to be updated to match the new naming scheme for classes (I'm aware its still backwards compatible but might as well be consistent from the start)

**Comment by Poulern** [comment]
Is this with the latest dev branch missions.sqm? I Have updated the relevant fields there already for the latest PR (I committed the changes sunday 22 NOV)

**Comment by thepaullee** [comment]
Ah yes, disregard closing issue
